apiVersion: apps/v1
kind: Deployment
metadata:
    name: platforms-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: platformservice
    template:
        metadata:
            labels:
                app: platformservice
        spec:
            containers:
                - name: platformservice
                  image: fbr41763/platformservice:latest
                  # ports:
                  #     - containerPort: 8080
