apiVersion: v1
kind: Service
metadata:
    name: platformservice-srv
spec:
    selector:
        app: platformservice
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
    type: NodePort
